### ISSUE TITLE
Test harnes Leader 9.2.6 fail

### ISSUE THREAD

**Issue by GabrielCouturier** [openthread/ot-nxp#264]
#### Problem
Running on NXP K32W061 board.
Test harness Leader 9.2.6 fail at step :
Check if Data Response packet has Security
Policy TLV in Active Operational Dataset : Security
Policy sub TLV not present

See attached logs 
[Fail_OT_NXP_9_2_6_Leader_v54.4_2022_05_06-10_51_02.zip](https://github.com/openthread/ot-nxp/files/8700465/Fail_OT_NXP_9_2_6_Leader_v54.4_2022_05_06-10_51_02.zip)

After doing the bisection :
It starts failing with :
https://github.com/openthread/ot-nxp/commit/f68cedc102

This open thread submodule update correspond to one change in the open thread stack :
https://github.com/openthread/openthread/commit/a8b4fbb1893823e1c247ee1cc

**Comment by GabrielCouturier** [comment]
I have opened the same issue on the OT github :
https://github.com/openthread/openthread/issues/7701

**Comment by jwhui** [comment]
@GabrielCouturier , it looks like the Security Policy TLV is not getting configured properly.

We did make a recent change to the Security Policy TLV to reflect the removal of the 'b' flag from the Thread Specification (see https://github.com/openthread/openthread/pull/7472). One possibility is that you need to account for this update in the Test Harness integration.

**Comment by jwhui** [comment]
Closing stale issue.
