### ISSUE TITLE
the PACKAGE_VERSION is not updated

### ISSUE THREAD

**Issue by doru91** [openthread/ot-nxp#44]
The output of the 'version' cli command contains the PACKAGE_VERSION.  The PACKAGE_VERSION should be updated to the commit id of the code that was used for compilation but this doesn't happen. I investigated the build system files and the default openthread version is taken from the file ./openthread/.default-version.

What is the correct path for populating the PACKAGE_VERSION?

> version
OPENTHREAD/**0.01.00**; K32W061; Jun  9 2021 02:40:31

@jwhui

**Comment by jwhui** [comment]
@doru91 , thanks for raising this issue.

I have submitted a proposed fix in https://github.com/openthread/openthread/pull/6717. Please review.

**Comment by jwhui** [comment]
@doru91 , I have submitted https://github.com/openthread/ot-nxp/pull/53. Please review.
