### ISSUE TITLE
Toolchain Installation

### ISSUE THREAD

**Issue by wolfpack51** [openthread/ot-nxp#478]
Is it possible to ask a question here?  I receive an error when running ./script/bootstrap

++ dirname ./script/bootstrap
+ ./script/../openthread/script/bootstrap
./script/bootstrap: line 32: ./script/../openthread/script/bootstrap: No such file or directory

I have cloned everything and looked at the bootstrap but am not able to figure out what is going on.  I know this was commit 2 years ago so it must work.
If I should not ask this question (i did submit a support ticket) please let me know and you will not hear from me again.  Thank yuou.

**Comment by jwhui** [comment]
This repo includes git submodules, which also need to be cloned with the following command:
```
git submodule update --init
```

**Comment by wolfpack51** [comment]
Thank you Jonathan.  Very much appreciate you responding.

Rick Cartier
***@***.***

**Comment by wolfpack51** [comment]
Jonathan – another question.  I am not sure if I should ask via github, here, or not ask at all.  I was able clone the matter repository.  Following the directions at ot-nxp/README.md at main · openthread/ot-nxp (github.com)<https://github.com/openthread/ot-nxp/blob/main/src/k32w0/k32w061/README.md>

I downloaded and installed MCUXpresso, downloaded the corresponding SDK and then opened MCUXpresso and added the SDK.  The instructions seem to tell me to go to the folder where I extracted the SDK – which is shown below

C:\Users\rick.cartier\Downloads\SDK_2_6_10_K32W061DK6

Since I am running Ubuntu in windows, the path is actually

mnt/c/Users……/Downloads/SDK_2_6_10_K32W061DK6

if I *ls* or some other linux command with the above path, it is recognized.  However I am completely not able to build this – can you look at this below and offer any insight?  I understand this is not something I expect you do so if I need to open a support ticket I can do that.  I’m trying to work through this so I can help our customers (ironic when I cant do it) but that’s my motivation here.  Thank you.

***@***.***


Rick Cartier
***@***.***

**Comment by wolfpack51** [comment]
Hello - The above worked.  As an aside, I am not able to build on Ubuntu running under Windows but on a Linux machine it seemed to work except there is an error when I build - i have pasted it below but it is looking for generic_list.c and in the SDK (downloaded at the above link) the file in the directory is labeled fsl_component_generic_list.c
**********************************************************************
CMake Error at third_party/k32w061_sdk/CMakeLists.txt:36 (add_library):
   Cannot find source file:

/home/rick/mcuxpresso/02/SDKPackages/components/lists/generic_list.c

   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
   .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at third_party/k32w061_sdk/CMakeLists.txt:36 (add_library):
   No SOURCES given to target: nxp-k32w061-driver
**********************************************************************

Renaming the file to what it looks for (generic_list.c) does not work.  Rebuilding then fails as fsl_component_generic_list.h is referenced and compile fails.  Any thoughts on this?
