### ISSUE TITLE
Running RCP Image on Ubuntu System and Unable to establish communication Between RCP and OTBR-AGENT (Openthread communication)

### ISSUE THREAD

**Issue by dipVyas92** [openthread/ot-nxp#491]
I have purchased new K32W USB dongles. I am trying to run openthread sample example on an Ubuntu machine with a K32W dongle.

I have created RCP image for k32w dongle from openthread github.(**https://github.com/openthread/ot-nxp/blob/main/src/k32w0/k32w061/README.md**) (commit id :: **f8d5376ef1e958d2e59f4afa2587a1dbdf092c6f**)

I am running otbr-agent on the **ubuntu(v22.02)** PC using the following command from ot-br-posix GitHub (**https://openthread.io/guides/border-router**) (commit id :: **495612f696947fc38dc71e8ee3378477378cf144** )

I have used the main branch from the repo for the otbr-agent and RCP image.

#/usr/sbin/otbr-agent -I wpan0 -B enp1s0 spinel+hdlc+uart:///dev/ttyUSB0 trel://enp1s0

But the otbr-agent is failing to communicate with the K32W dongle and giving the following error

otbr-agent[33585]: [NOTE]-AGENT---: Running 0.3.0-1612526196
otbr-agent[33585]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[33585]: [NOTE]-AGENT---: Thread interface: enp1s0
otbr-agent[33585]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB0
otbr-agent[33585]: [NOTE]-AGENT---: Radio URL: trel://enp1s0
otbr-agent[33585]: [NOTE]-ILS-----: Infra link selected: enp1s0
otbr-agent[33585]: [INFO]-NCP-----: OpenThread log level changed to 4
otbr-agent[33585]: 49d.18:56:15.522 [W] Platform------: Wait for response timeout
otbr-agent[33585]: 49d.18:56:15.523 [I] Platform------: Software reset RCP successfully
otbr-agent[33585]: 49d.18:56:17.525 [W] Platform------: Wait for response timeout
otbr-agent[33585]: 49d.18:56:17.525 [C] Platform------: **HandleRcpTimeout() at radio_spinel_impl.hpp:2301: RadioSpinelNoResponse**
systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 677.
systemd[1]: Stopped OpenThread Border Router Agent.
systemd[1]: Starting OpenThread Border Router Agent...
systemd[1]: Started OpenThread Border Router Agent.
otbr-agent: [NOTE]-AGENT---: Backbone interface: enp1s0

Would you like me to make specific changes to communicate over USB for the dongle?

is there any ready example for an open thread RCP Image present for k32w?

**Comment by mihai-ignat** [comment]
Hello, @dipVyas92 .
OT RCP support for the USB dongle is not publicly available. This is due to issues identified on OpenThread conformance for version 1.3 which are under internal investigation. We do have a version which is OT 1.1 certifiable which can be shared if you open a community post at [this location](https://community.nxp.com/t5/Wireless-Connectivity/bd-p/wireless-connectivity). We can have further discussions there regarding your projects that use NXP products.
BR
Mihai

**Comment by dipVyas92** [comment]
> 

Hello, @mihai-ignat .

Thanks for the response.

I tried with SDK(v2.6.10) RCP binary file but got the same error with the OTBR agent(commit id:: https://github.com/openthread/ot-nxp/commit/f8d5376ef1e958d2e59f4afa2587a1dbdf092c6f).

**Comment by mihai-ignat** [comment]
Hello, @dipVyas92 .
Indeed, I forgot to mention an update to the otbr-agent command. You need to add `?uart-baudrate=1000000`. Please see my output from below:

`$ sudo otbr-agent -I wpan0 -B wlo1 spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=1000000 -v trel://wlo1
otbr-agent[3960]: [NOTE]-AGENT---: Running 0.3.0-c8d51a2bbe
otbr-agent[3960]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[3960]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[3960]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=1000000
otbr-agent[3960]: [NOTE]-AGENT---: Radio URL: trel://wlo1
otbr-agent[3960]: [NOTE]-ILS-----: Infra link selected: wlo1
otbr-agent[3960]: [INFO]-NCP-----: OpenThread log level changed to 4
otbr-agent[3960]: 49d.17:05:08.708 [I] Platform------: RCP reset: RESET_POWER_ON
otbr-agent[3960]: 49d.17:05:08.708 [I] Platform------: Software reset RCP successfully
otbr-agent[3960]: 49d.17:05:08.805 [I] Platform------: Backbone interface is configured to wlo1 (3)
otbr-agent[3960]: 49d.17:05:08.808 [I] Platform------: [netif] Sent request#1 to set addr_gen_mode to 1
otbr-agent[3960]: 00:00:00.236 [I] ChildSupervsn-: Timeout: 0 -> 190
otbr-agent[3960]: 00:00:00.236 [I] InfraIf-------: Init infra netif 3
otbr-agent[3960]: 00:00:00.236 [I] Settings------: Read BrUlaPrefix fdeb:ba16:8cec::/48
otbr-agent[3960]: 00:00:00.236 [N] BorderRouter--: BR ULA prefix: fdeb:ba16:8cec::/48 (loaded)
otbr-agent[3960]: 00:00:00.236 [I] BorderRouter--: Generated OMR prefix: fdeb:ba16:8cec:1::/64
otbr-agent[3960]: 00:00:00.236 [I] BorderRouter--: Generated local NAT64 prefix: fdeb:ba16:8cec:2:0:0::/96
otbr-agent[3960]: 00:00:00.236 [N] BorderRouter--: Local on-link prefix: fdde:ad00:beef:cafe::/64
otbr-agent[3960]: 00:00:00.236 [I] InfraIf-------: State changed: NOT RUNNING -> RUNNING
otbr-agent[3960]: 00:00:00.237 [C] Platform------: Got nameserver #0: 127.0.0.53
otbr-agent[3960]: [INFO]-UTILS---: Set state callback: OK
otbr-agent[3960]: 00:00:00.237 [I] Nat64---------: NAT64 translator is now NotRunning
otbr-agent[3960]: [INFO]-BA------: Publish meshcop service OpenThread BorderRouter #A7A7._meshcop._udp.local.
otbr-agent[3960]: [INFO]-MDNS----: Registering new service OpenThread BorderRouter #A7A7._meshcop._udp.local, serviceRef = (nil)
otbr-agent[3960]: [INFO]-ADPROXY-: Publish all hosts and services
otbr-agent[3960]: [INFO]-ADPROXY-: Started
otbr-agent[3960]: [INFO]-DPROXY--: Started
otbr-agent[3960]: [INFO]-BA------: Start Thread Border Agent: OK
otbr-agent[3960]: 00:00:00.237 [I] BbrLocal------: Add Domain Prefix: ::/0, NotFound
otbr-agent[3960]: 00:00:00.237 [I] BbrLocal------: Add BBR Service: seqno (33), delay (5s), timeout (3600s), InvalidState
otbr-agent[3960]: [INFO]-APP-----: Thread Border Router started on AIL wlo1.
otbr-agent[3960]: 00:00:00.238 [I] Notifier------: StateChanged (0x42038200) [NetData PanId NetName ExtPanId BbrState (unknown)]
otbr-agent[3960]: 00:00:00.238 [I] Bbr-----------: Backbone TMF subscribes ff32:40:fdde:ad00:beef:0:0:3: OK
otbr-agent[3960]: 00:00:00.238 [I] BbrManager----: Start Backbone TMF agent: OK
otbr-agent[3960]: 00:00:00.239 [I] Platform------: Execute command `ipset flush otbr-ingress-allow-dst-swap` = 0
otbr-agent[3960]: 00:00:00.240 [I] Platform------: Execute command `ipset flush otbr-ingress-deny-src-swap` = 0
otbr-agent[3960]: 00:00:00.241 [I] Platform------: Execute command `ipset add otbr-ingress-deny-src-swap fdde:ad00:beef:0::/64 -exist` = 0
otbr-agent[3960]: 00:00:00.242 [I] Platform------: Execute command `ipset swap otbr-ingress-deny-src-swap otbr-ingress-deny-src` = 0
otbr-agent[3960]: 00:00:00.243 [I] Platform------: Execute command `ipset swap otbr-ingress-allow-dst-swap otbr-ingress-allow-dst` = 0
otbr-agent[3960]: 00:00:00.243 [I] Platform------: MulticastRoutingManager: Disable: OK
otbr-agent[3960]: [INFO]-BA------: Publish meshcop service OpenThread BorderRouter #A7A7._meshcop._udp.local.
otbr-agent[3960]: 00:00:00.243 [I] RouterTable---: Route table
otbr-agent[3960]: 00:00:00.252 [I] Platform------: [netif] Host netif is down
otbr-agent[3960]: 00:00:00.252 [I] Platform------: [netif] Succeeded to process request#1
otbr-agent[3960]: [INFO]-MDNS----: Received reply for service OpenThread BorderRouter #A7A7._meshcop._udp., serviceRef = 0x558f077f6db0
otbr-agent[3960]: [INFO]-MDNS----: Successfully registered service OpenThread BorderRouter #A7A7._meshcop._udp.
otbr-agent[3960]: [INFO]-BA------: Result of publish meshcop service OpenThread BorderRouter #A7A7._meshcop._udp.local: OK
otbr-agent[3960]: [INFO]-BA------: Result of publish meshcop service OpenThread BorderRouter #A7A7._meshcop._udp.local: OK`

BR,
Mihai

**Comment by mihai-ignat** [comment]
Hello, @dipVyas92 .
Can you confirm that the proposed fix is working?
BR,
Mihai

**Comment by dipVyas92** [comment]
Hi @mihai-ignat ,

Thanks for the solution.

I have tried it with my Linux system, It is working as required.
Thank you once again
