### ISSUE TITLE
[spinel] build failing with radio spinel update

### ISSUE THREAD

**Issue by jwhui** [openthread/ot-nxp#608]
- https://github.com/openthread/ot-nxp/pull/607
- https://github.com/openthread/ot-nxp/actions/runs/6482146392/job/17601092213?pr=607

**Comment by zhanglongxia** [comment]
Hi Jonathan, I have pushed a commit https://github.com/openthread/ot-nxp/pull/609 to fix this issue. Do you know how to put the commit https://github.com/openthread/ot-nxp/pull/609 and https://github.com/openthread/ot-nxp/pull/607 to the same topic to pass the github action tests?

**Comment by zhanglongxia** [comment]
I directly updated the OpenThread to the latest version in the https://github.com/openthread/ot-nxp/pull/609 to avoid the github action failure issue.
