### ISSUE TITLE
Is example working on JN5189 Dongle not DK6?

### ISSUE THREAD

**Issue by wootak-jung** [openthread/ot-nxp#88]
Hello,

I'm following the NXP JN5189 example guide in below with JN5189 USB Dongle:
Example Guide: https://github.com/openthread/ot-nxp/blob/main/src/k32w/jn5189/README.md
JN5189 USB Dongle: www.nxp.com/OM15080-JN5189

But, this guide seems for JN5189DK6 not Dongle.
Is there any example guide for JN5189 Dongle?
And, actually I want to run and test for ot-br-posix OpenThread Border Router in Linux, is it possible?
example guide seems to be run on Windows.

Please kindly guide me.
Thank you

**Comment by doru91** [comment]
Hi, @Wootak 

My understanding is that you want to run ot-br-posix using JN5189 USB Dongle as RCP. If this is the case, then the ot-rcp.bin image can be flashed on the USB Dongle using DK6Programmer (instructions are similar with the one for DK6):

```
C:\nxp\DK6ProductionFlashProgrammer>DK6Programmer.exe  --list
Available connections:
COM29
```
Once the COM port is identified, the required binary can be flashed:

`C:\nxp\DK6ProductionFlashProgrammer>DK6Programmer.exe -s COM29 -p ot-rcp.bin`

The ot-br-posix is designed to run in Linux, only the RCP image needs to be flashed with a Windows application (DK6Programmer).

Hope it helps.

**Comment by Wootak** [comment]
Thanks for your reply!

Actually, I can't flash the image by using DK6Programmer because JN5189 Dongle is not identified in my Windows 10 PC like below.
```
C:\NXP\DK6ProductionFlashProgrammer>DK6Programmer.exe --list
Available connections:
COM1
```
My doubt is in following DK6Programmer guide. Is this guide not mandatory setting to identify COM port?
> Using DK6Programmer
> Connect to the DK6 board by plugging a mini-USB cable to the connector marked with FTDI USB. Also, **make sure that jumpers jp4/JP7 are situated in the middle position (JN UART0 - FTDI).**

Otherwise, if there is a guide page to setup JN5189 Dongle, it will be very helpful to me!

**Comment by curve86** [comment]
i think you should not install the driver for FTDI USB to UART chip.
please download the driver from https://ftdichip.com/drivers/d2xx-drivers/
select X86 or X64 base on your Window OS
and install the driver when plug the USB into your PC

**Comment by curve86** [comment]
attach more information
if the USB dongle is from NXP, then skip this. but if the USB dongle is done from customer, this procedure shoud be noted
https://www.nxp.com/downloads/en/design-support/JN-RD-6021.zip
in the document, you should use FT_Prog to configure the IO for FTDI chip

![FT_Prog configure](https://user-images.githubusercontent.com/7940537/130724704-e3d2b5d9-fad5-480f-9e28-85bf30d1d7ce.jpg)

install the FT_Prog software on you PC (https://ftdichip.com/utilities/)
and scan the devices, configure the IO_Controls
C0  TXLED
C1  RXLED
C2  I/O MODE
C3  I/O MODE

**Comment by jwhui** [comment]
Closing stale issue.
